name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME"
          heroku_email: 'YOUR EMAIL'
          usedocker: true
          appdir: 'Codigo'
          docker_build_args: |
            NODE_ENV
            SECRET
            SHOPIFY_ADMIN_TOKEN
            SHOPIFY_STOREFRONT_TOKEN
            SHOPIFY_URL
            PORT
            ORIGIN_URL
            DB_TYPE
            DB_HOST
            DB_PORT
            DB_DATABASE
            DB_USER
            DB_PASSWORD
            SKIP_PREFLIGHT_CHECK
            AWS_S3_BUCKET
            AWS_S3_BUCKET_URL
            AWS_S3_REGION
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            LOCALSTACK_S3_ENDPOINT
            EMAIL_FROM
            EMAIL_SMTP_HOST
            EMAIL_SMTP_PORT
            EMAIL_SMTP_USER
            EMAIL_SMTP_PASS
        env:
          NODE_ENV: production
          SECRET: ${{ secrets.SECRET_KEY }}
          SHOPIFY_ADMIN_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
          SHOPIFY_STOREFRONT_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_TOKEN }}
          SHOPIFY_URL: ${{ secrets.SHOPIFY_URL }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_URL: ${{ secrets.ORIGIN_URL }}
          DB_TYPE: ${{ secrets.DB_TYPE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SKIP_PREFLIGHT_CHECK: true
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_BUCKET_URL: ${{ secrets.AWS_S3_BUCKET_URL }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LOCALSTACK_S3_ENDPOINT: ${{ secrets.LOCALSTACK_S3_ENDPOINT }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
          EMAIL_SMTP_PASS: ${{ secrets.EMAIL_SMTP_PASS }}
